In [18]:
#This notebook includes the import of csv file and then use only the necessary columns
#some cleaning is also done like removing country codes
import pandas as pd

df = pd.read_csv("sportsref_download-2.csv")

df = df[['Home', 'Away', 'Score']].dropna()
df = df[df['Home'] != 'Home'].copy()

# Remove country codes
df['Home'] = df['Home'].str.rsplit(' ', n=1).str[0]
df['Away'] = df['Away'].str.split(' ', n=1).str[1]

df = df.replace({
    'USA': 'United States',
    'Bosnia–Herz': 'Bosnia and Herzegovina',
    'Korea Republic': 'South Korea',
    'IR Iran': 'Iran',
    'Congo DR': 'Democratic Republic of the Congo'
})

# Extract goals, excluding penalty shoot-out numbers
goals = df['Score'].str.extract(r'(\d+)[–-](\d+)').astype(int)
df['Goal_Difference'] = goals[0] - goals[1]

df = df[['Home', 'Away', 'Goal_Difference']]
df.to_csv('match_teams_goal_difference.csv', index=False)

df.head()

            Home                    Away  Goal_Difference
0         Mexico            South Africa                2
1    South Korea                 Czechia                1
2         Canada  Bosnia and Herzegovina                0
3  United States                Paraguay                3
4          Qatar             Switzerland                0

In [19]:
#2025 international games were taken manually from "https://inside.fifa.com/data-centre/teams/cabo-verde?year=2025" website
#from that website, total matches, wins, draws, defeats, goal scored, goal conceded were taken

import pandas as pd

teams = pd.read_excel("2025_games.xlsx")
#calculation of variables
teams["Win_Rate"] = teams["Wins"] / teams["Total matches"]
teams["Draw_Rate"] = teams["Draws"] / teams["Total matches"]
teams["Avg_Scored"] = teams["Goals scored"] / teams["Total matches"]
teams["Avg_Conceded"] = teams["Goals conceded"] / teams["Total matches"]

teams.to_csv("country_variables_2025.csv", index=False)

teams.head()

,Team,Total matches,Wins,Draws,Defeats,Goals scored,Goals conceded,Win_Rate,Draw_Rate,Avg_Scored,Avg_Conceded
0,Algeria,24,15,8,1,50,15,0.625000,0.333333,2.083333,0.625000
1,Argentina,9,7,1,1,19,3,0.777778,0.111111,2.111111,0.333333
2,Australia,10,7,0,3,16,9,0.700000,0.000000,1.600000,0.900000
3,Austria,10,6,2,2,23,7,0.600000,0.200000,2.300000,0.700000
4,Belgium,10,6,3,1,33,10,0.600000,0.300000,3.300000,1.000000